fixed: undefined method `execute' for class `Rake::Task' (NameError)
If just to require the gem for Ruby, (e.g. run `ruby -rrake/delphi -e 'puts RUBY_VERSION'`)
then "undefined method `execute' for class `Rake::Task' (NameError)" is
occured.

Fix it with "require 'rake'" in appropriate modules. Also, avoid similar
possible error with gem `logger`